
module Words where
     
import qualified Data.Set as S 

allWords = S.unions [preposistionSet ,adverbSet, verbSet, nounSet, adjectivesSet, connectiveSet, pronounSet]

preposistionSet = S.fromList preposistions

preposistions = [
    "aboard","about","above","according to","across","after","against","ahead of","along","amid","amidst","among","around","as","as far as","as of","aside from","at","athwart","atop",

    "barring","because of","before","behind","below","beneath","beside","besides","between","beyond","but (when it means except)","by","by means of",

    "circa","concerning",

    "despite","down","due to","during",

    "except","except for","excluding",

    "far from","following","for","from",

    "in","in accordance with","in addition to","in case of","in front of","in lieu of","in place of","in spite of","including","inside","instead of","into",

    "like",

    "minus",

    "near","next to","notwithstanding",

    "of","off","on","on account of","on behalf of","on top of","onto","opposite","out","out of","outside","over",

    "past","plus","prior to",

    "regarding","regardless of",

    "save","since",

    "than","through","throughout","till","to","toward","towards",

    "under","underneath","unlike","until","up","upon",

    "versus","via",

    "with","with regard to","within","without"]

connectiveSet = S.fromList connectives


connectives = ["and"," also"," besides"," further"," furthermore"," too"," moreover"," in addition"," then"," of equal importance"," equally important"," another",
	"next"," afterward"," finally"," later"," last"," lastly"," at last"," now"," subsequently"," then"," when"," soon"," thereafter"," after a short time"," the next week (month"," day"," etc.)"," a minute later"," in the meantime"," meanwhile"," on the following day"," at length"," ultimately"," presently",

	"first"," second"," (etc.)"," finally"," hence"," next"," then"," from here on"," to begin with"," last of all"," after"," before"," as soon as"," in the end"," gradually",
	"above"," behind"," below"," beyond"," here"," there"," to the right (left)"," nearby"," opposite"," on the other side"," in the background"," directly ahead"," along the wall"," as you turn right"," at the top"," across the hall"," at this point"," adjacent to",

	"for example"," to illustrate"," for instance"," to be specific"," such as"," moreover"," furthermore"," just as important"," similarly"," in the same way",
	"as a result"," hence"," so"," accordingly"," as a consequence"," consequently"," thus"," since"," therefore"," for this reason","because of this",
	"to this end"," for this purpose"," with this in mind"," for this reason(s)"
  ]

adverbSet = S.fromList ["abnormally","absentmindedly","accidentally","actually","adventurously","afterwards","almost","always","annually","anxiously","arrogantly","awkwardly","bashfully","beautifully","bitterly","bleakly","blindly","blissfully","boastfully","boldly","bravely","briefly","brightly","briskly","broadly","busily","calmly","carefully","carelessly","cautiously","certainly","cheerfully","clearly","cleverly","closely","coaxingly","colorfully","commonly","continually","coolly","correctly","courageously","crossly","cruelly","curiously","daily","daintily","dearly","deceivingly","deeply","defiantly","deliberately","delightfully","diligently","dimly","doubtfully","dreamily","easily","elegantly","energetically","enormously","enthusiastically","equally","especially","even","evenly","eventually","exactly","excitedly","extremely","fairly","faithfully","famously","far","fast","fatally","ferociously","fervently","fiercely","fondly","foolishly","fortunately","frankly","frantically","freely","frenetically","frightfully","fully","furiously","generally","generously","gently","gladly","gleefully","gracefully","gratefully","greatly","greedily","happily","hastily","healthily","heavily","helpfully","helplessly","highly","honestly","hopelessly","hourly","hungrily","immediately","innocently","inquisitively","instantly","intensely","intently","interestingly","inwardly","irritably","jaggedly","jealously","jovially","joyfully","joyously","jubilantly","judgmentally","justly","keenly","kiddingly","kindheartedly","kindly","knavishly","knowingly","knowledgeably","kookily","lazily","les","lightly","likely","limply","lively","loftily","longingly","loosely","loudly","lovingly","loyally","madly","majestically","meaningfully","mechanically","merrily","miserably","mockingly","monthly","more","mortally","mostly","mysteriously","naturally","hopelessly","hourly","hungrily","immediately","innocently","inquisitively","instantly","intensely","intently","interestingly","inwardly","irritably","jaggedly","jealously","jovially","joyfully","joyously","jubilantly","judgmentally","justly","keenly","kiddingly","kindheartedly","kindly","knavishly","knowingly","knowledgeably","kookily","lazily","less","lightly","likely","limply","lively","loftily","longingly","loosely","loudly","lovingly","loyally","madly","majestically","meaningfully","mechanically","merrily","miserably","mockingly","monthly","more","mortally","mostly","mysteriously","naturally","nearly","neatly","nervously","never","nicely","noisily","not","obediently","obnoxiously","oddly","offensively","officially","often","only","openly","optimistically","overconfidently","painfully","partially","patiently","perfectly","physically","playfully","politely","poorly","positively","potentially","powerfully","promptly","properly","punctually","quaintly","queasily","queerly","questionably","quicker","quickly","quietly","quirkily","quizzically","randomly","rapidly","rarely","readily","really","reassuringly","recklessly","regularly","reluctantly","repeatedly","reproachfully","restfully","righteously","rightfully","rigidly","roughly","rudely","safely","scarcely","scarily","searchingly","sedately","seemingly","seldom","selfishly","separately","seriously","shakily","sharply","sheepishly","shrilly","shyly","silently","sleepily","slowly","smoothly","softly","solemnly","solidly","sometimes","soon","speedily","stealthily","sternly","strictly","successfully","suddenly","supposedly","surprisingly","suspiciously","sweetly","swiftly","sympathetically","tenderly","tensely","terribly","thankfully","thoroughly","thoughtfully","tightly","tomorrow","too","tremendously","triumphantly","truly","truthfully","rightfully","scarcely","searchingly","sedately","seemingly","selfishly","separately","seriously","sheepishly","smoothly","solemnly","sometimes","speedily","stealthily","successfully","suddenly","supposedly","surprisingly","suspiciously","sympathetically","tenderly","thankfully","thoroughly","thoughtfully","tomorrow","tremendously","triumphantly","truthfully","ultimately","unabashedly","unaccountably","unbearably","unethically","unexpectedly","unfortunately","unimpressively","unnaturally","unnecessarily","upbeat","upright","upside","down","upward","urgently","usefully","uselessly","usually","utterly","vacantly","vaguely","vainly","valiantly","vastly","verbally","very","viciously","victoriously","violently","vivaciously","voluntarily","warmly","weakly","wearily","well","wetly","wholly","wildly","willfully","wisely","woefully","wonderfully","worriedly","wrongly","yawningly","yearly","yearningly","yesterday","yieldingly","youthfully","zealously","zestfully","zestily"] 

pronounSet = S.fromList pronouns

pronouns = ["all",
    "another",
    "any",
    "anybody",
    "anyone",
    "anything",
    "both",
    "each",
    "each", "other",
    "either",
    "everybody",
    "everyone",
    "everything",
    "few",



    "he",
    "her",
    "hers",
    "herself",
    "him",
    "himself",
    "his",



    "I",
    "it",
    "its",
    "itself",



    "little",



    "many",
    "me",
    "mine",
    "more",
    "most",
    "much",
    "my",
    "myself",



    "neither",
    "no", "one",
    "nobody",
    "none",
    "nothing",



    "one",
    "one", "another",
    "other",
    "others",
    "our",
    "ours",
    "ourselves",



    "several",
    "she",
    "some",
    "somebody",
    "someone",
    "something",



    "that",
    "their",
    "theirs",
    "them",
    "themselves",
    "these",
    "they",
    "this",
    "those",



    "us",



    "we",
    "what",
    "whatever",
    "which",
    "whichever",
    "who",
    "whoever",
    "whom",
    "whomever",
    "whose",



    "you",
    "your",
    "yours",
    "yourself",
    "yourselves"]

nounSet = S.fromList nouns

nouns = ["people",
    "history",
    "way",
    "art",
    "world",
    "information",
    "map",
    "two",
    "family",
    "government",
    "health",
    "system",
    "computer",
    "meat",
    "year",
    "thanks",
    "music",
    "person",
    "reading",
    "method",
    "data",
    "food",
    "understanding",
    "theory",
    "law",
    "bird",
    "literature",
    "problem",
    "software",
    "control",
    "knowledge",
    "power",
    "ability",
    "economics",
    "love",
    "internet",
    "television",
    "science",
    "library",
    "nature",
    "fact",
    "product",
    "idea",
    "temperature",
    "investment",
    "area",
    "society",
    "activity",
    "story",
    "industry",
    "media",
    "thing",
    "oven",
    "community",
    "definition",
    "safety",
    "quality",
    "development",
    "language",
    "management",
    "player",
    "variety",
    "video",
    "week",
    "security",
    "country",
    "exam",
    "movie",
    "organization",
    "equipment",
    "physics",
    "analysis",
    "policy",
    "series",
    "thought",
    "basis",
    "boyfriend",
    "direction",
    "strategy",
    "technology",
    "army",
    "camera",
    "freedom",
    "paper",
    "environment",
    "child",
    "instance",
    "month",
    "truth",
    "marketing",
    "university",
    "writing",
    "article",
    "department",
    "difference",
    "goal",
    "news",
    "audience",
    "fishing",
    "growth",
    "income",
    "marriage",
    "user",
    "combination",
    "failure",
    "meaning",
    "medicine",
    "philosophy",
    "teacher",
    "communication",
    "night",
    "chemistry",
    "disease",
    "disk",
    "energy",
    "nation",
    "road",
    "role",
    "soup",
    "advertising",
    "location",
    "success",
    "addition",
    "apartment",
    "education",
    "math",
    "moment",
    "painting",
    "politics",
    "attention",
    "decision",
    "event",
    "property",
    "shopping",
    "student",
    "wood",
    "competition",
    "distribution",
    "entertainment",
    "office",
    "population",
    "president",
    "unit",
    "category",
    "cigarette",
    "context",
    "introduction",
    "opportunity",
    "performance",
    "driver",
    "flight",
    "length",
    "magazine",
    "newspaper",
    "relationship",
    "teaching",
    "cell",
    "dealer",
    "finding",
    "lake",
    "member",
    "message",
    "phone",
    "scene",
    "appearance",
    "association",
    "concept",
    "customer",
    "death",
    "discussion",
    "housing",
    "inflation",
    "insurance",
    "mood",
    "woman",
    "advice",
    "blood",
    "effort",
    "expression",
    "importance",
    "opinion",
    "payment",
    "reality",
    "responsibility",
    "situation",
    "skill",
    "statement",
    "wealth",
    "application",
    "city",
    "county",
    "depth",
    "estate",
    "foundation",
    "grandmother",
    "heart",
    "perspective",
    "photo",
    "recipe",
    "studio",
    "topic",
    "collection",
    "depression",
    "imagination",
    "passion",
    "percentage",
    "resource",
    "setting",
    "ad",
    "agency",
    "college",
    "connection",
    "criticism",
    "debt",
    "description",
    "memory",
    "patience",
    "secretary",
    "solution",
    "administration",
    "aspect",
    "attitude",
    "director",
    "personality",
    "psychology",
    "recommendation",
    "response",
    "selection",
    "storage",
    "version",
    "alcohol",
    "argument",
    "complaint",
    "contract",
    "emphasis",
    "highway",
    "loss",
    "membership",
    "possession",
    "preparation",
    "steak",
    "union",
    "agreement",
    "cancer",
    "currency",
    "employment",
    "engineering",
    "entry",
    "interaction",
    "mixture",
    "preference",
    "region",
    "republic",
    "tradition",
    "virus",
    "actor",
    "classroom",
    "delivery",
    "device",
    "difficulty",
    "drama",
    "election",
    "engine",
    "football",
    "guidance",
    "hotel",
    "owner",
    "priority",
    "protection",
    "suggestion",
    "tension",
    "variation",
    "anxiety",
    "atmosphere",
    "awareness",
    "bath",
    "bread",
    "candidate",
    "climate",
    "comparison",
    "confusion",
    "construction",
    "elevator",
    "emotion",
    "employee",
    "employer",
    "guest",
    "height",
    "leadership",
    "mall",
    "manager",
    "operation",
    "recording",
    "sample",
    "transportation",
    "charity",
    "cousin",
    "disaster",
    "editor",
    "efficiency",
    "excitement",
    "extent",
    "feedback",
    "guitar",
    "homework",
    "leader",
    "mom",
    "outcome",
    "permission",
    "presentation",
    "promotion",
    "reflection",
    "refrigerator",
    "resolution",
    "revenue",
    "session",
    "singer",
    "tennis",
    "basket",
    "bonus",
    "cabinet",
    "childhood",
    "church",
    "clothes",
    "coffee",
    "dinner",
    "drawing",
    "hair",
    "hearing",
    "initiative",
    "judgment",
    "lab",
    "measurement",
    "mode",
    "mud",
    "orange",
    "poetry",
    "police",
    "possibility",
    "procedure",
    "queen",
    "ratio",
    "relation",
    "restaurant",
    "satisfaction",
    "sector",
    "signature",
    "significance",
    "song",
    "tooth",
    "town",
    "vehicle",
    "volume",
    "wife",
    "accident",
    "airport",
    "appointment",
    "arrival",
    "assumption",
    "baseball",
    "chapter",
    "committee",
    "conversation",
    "database",
    "enthusiasm",
    "error",
    "explanation",
    "farmer",
    "gate",
    "girl",
    "hall",
    "historian",
    "hospital",
    "injury",
    "instruction",
    "maintenance",
    "manufacturer",
    "meal",
    "perception",
    "pie",
    "poem",
    "presence",
    "proposal",
    "reception",
    "replacement",
    "revolution",
    "river",
    "son",
    "speech",
    "tea",
    "village",
    "warning",
    "winner",
    "worker",
    "writer",
    "assistance",
    "breath",
    "buyer",
    "chest",
    "chocolate",
    "conclusion",
    "contribution",
    "cookie",
    "courage",
    "dad",
    "desk",
    "drawer",
    "establishment",
    "examination",
    "garbage",
    "grocery",
    "honey",
    "impression",
    "improvement",
    "independence",
    "insect",
    "inspection",
    "inspector",
    "king",
    "ladder",
    "menu",
    "penalty",
    "piano",
    "potato",
    "profession",
    "professor",
    "quantity",
    "reaction",
    "requirement",
    "salad",
    "sister",
    "supermarket",
    "tongue",
    "weakness",
    "wedding",
    "affair",
    "ambition",
    "analyst",
    "apple",
    "assignment",
    "assistant",
    "bathroom",
    "bedroom",
    "beer",
    "birthday",
    "celebration",
    "championship",
    "cheek",
    "client",
    "consequence",
    "departure",
    "diamond",
    "dirt",
    "ear",
    "fortune",
    "friendship",
    "funeral",
    "gene",
    "girlfriend",
    "hat",
    "indication",
    "intention",
    "lady",
    "midnight",
    "negotiation",
    "obligation",
    "passenger",
    "pizza",
    "platform",
    "poet",
    "pollution",
    "recognition",
    "reputation",
    "shirt",
    "sir",
    "speaker",
    "stranger",
    "surgery",
    "sympathy",
    "tale",
    "throat",
    "trainer",
    "uncle",
    "youth"
    ]


verbSet = S.fromList verbs

verbs = [
    "accept",
    "add",
    "admire",
    "admit",
    "advise",
    "afford",
    "agree",
    "alert",
    "allow",	"amuse",
    "analyse", 
    "analyze", 
    "announce",
    "annoy",
    "answer",
    "apologise",
    "appear",	"applaud",
    "appreciate",
    "approve",
    "argue",
    "arrange",
    "arrest",
    "arrive",
    "ask",	"attach",
    "attack",
    "attempt",
    "attend",
    "attract",
    "avoid",
    "back",
    "bake",
    "balance",
    "ban",
    "bang",
    "bare",
    "bat",
    "bathe",
    "battle",
    "beam",	"beg",
    "behave",
    "belong",
    "bleach",
    "bless",
    "blind",
    "blink",
    "blot",
    "blush",
    "boast",	"boil",
    "bolt",
    "bomb",
    "book",
    "bore",
    "borrow",
    "bounce",
    "bow",
    "box",
    "brake",	"branch",
    "breathe",
    "bruise",
    "brush",
    "bubble",
    "bump",
    "burn",
    "bury",
    "buzz",
    "calculate",
    "call",
    "camp",
    "care",
    "carry",
    "carve",
    "cause",
    "challenge",
    "change",
    "charge",
    "chase",
    "cheat",
    "check",
    "cheer",
    "chew",	"choke",
    "chop",
    "claim",
    "clap",
    "clean",
    "clear",
    "clip",
    "close",
    "coach",
    "coil",
    "collect",
    "colour",
    "comb",
    "command",
    "communicate",	"compare",
    "compete",
    "complain",
    "complete",
    "concentrate",
    "concern",
    "confess",
    "confuse",
    "connect",
    "consider",
    "consist",
    "contain",
    "continue",
    "copy",
    "correct",	"cough",
    "count",
    "cover",
    "crack",
    "crash",
    "crawl",
    "cross",
    "crush",
    "cry",
    "cure",
    "curl",
    "curve",
    "cycle",
    "dam",
    "damage",
    "dance",
    "dare",
    "decay",
    "deceive",
    "decide",
    "decorate",
    "delay",
    "delight",	"deliver",
    "depend",
    "describe",
    "desert",
    "deserve",
    "destroy",
    "detect",
    "develop",
    "disagree",
    "disappear",	"disapprove",
    "disarm",
    "discover",
    "dislike",
    "divide",
    "double",
    "doubt",
    "drag",
    "drain",
    "dream",	"dress",
    "drip",
    "drop",
    "drown",
    "drum",
    "dry",
    "dust",
    "earn",
    "educate",
    "embarrass",
    "employ",
    "empty",
    "encourage",	"end",
    "enjoy",
    "enter",
    "entertain",
    "escape",
    "examine",	"excite",
    "excuse",
    "exercise",
    "exist",
    "expand",
    "expect",	"explain",
    "explode",
    "extend",
    "face",
    "fade",
    "fail",
    "fancy",
    "fasten",
    "fax",
    "fear",
    "fence",	"fetch",
    "file",
    "fill",
    "film",
    "fire",
    "fit",
    "fix",
    "flap",	"flash",
    "float",
    "flood",
    "flow",
    "flower",
    "fold",
    "follow",
    "fool",	"force",
    "form",
    "found",
    "frame",
    "frighten",
    "fry",
    "gather",
    "gaze",
    "glow",
    "glue",	"grab",
    "grate",
    "grease",
    "greet",	"grin",
    "grip",
    "groan",
    "guarantee",	"guard",
    "guess",
    "guide",
    "hammer",
    "hand",
    "handle",
    "hang",
    "happen",
    "harass",	"harm",
    "hate",
    "haunt",
    "head",
    "heal",
    "heap",	"heat",
    "help",
    "hook",
    "hop",
    "hope",
    "hover",	"hug",
    "hum",
    "hunt",
    "hurry",
    "identify",
    "ignore",
    "imagine",
    "impress",
    "improve",
    "include",	"increase",
    "influence",
    "inform",
    "inject",
    "injure",
    "instruct",	"intend",
    "interest",
    "interfere",
    "interrupt",
    "introduce",
    "invent",	"invite",
    "irritate",
    "itch",
    "jail",
    "jam",	"jog",
    "join",	"joke",
    "judge",	"juggle",
    "jump",
    "kick",
    "kill",	"kiss",
    "kneel",	"knit",
    "knock",	"knot",
    "label",
    "land",
    "last",
    "laugh",
    "launch",	"learn",
    "level",
    "license",
    "lick",
    "lie",	"lighten",
    "like",
    "list",
    "listen",
    "live",	"load",
    "lock",
    "long",
    "look",
    "love",
    "man",
    "manage",
    "march",
    "mark",
    "marry",
    "match",
    "mate",	"matter",
    "measure",
    "meddle",
    "melt",
    "memorise",
    "mend",
    "mess", "up",	"milk",
    "mine",
    "miss",
    "mix",
    "moan",
    "moor",
    "mourn",	"move",
    "muddle",
    "mug",
    "multiply",
    "murder",
    "nail",
    "name",	"need",
    "nest",	"nod",
    "note",	"notice",
    "number",
    "obey",
    "object",
    "observe",	"obtain",
    "occur",
    "offend",	"offer",
    "open",
    "order",	"overflow",
    "owe",
    "own",
    "pack",
    "paddle",
    "paint",
    "park",
    "part",
    "pass",
    "paste",
    "pat",
    "pause",
    "peck",
    "pedal",
    "peel",
    "peep",
    "perform",
    "permit",	"phone",
    "pick",
    "pinch",
    "pine",
    "place",
    "plan",
    "plant",
    "play",
    "please",
    "plug",
    "point",
    "poke",
    "polish",
    "pop",	"possess",
    "post",
    "pour",
    "practise", 
    "practice", 
    "pray",
    "preach",
    "precede",
    "prefer",
    "prepare",
    "present",
    "preserve",
    "press",
    "pretend",	"prevent",
    "prick",
    "print",
    "produce",
    "program",
    "promise",
    "protect",
    "provide",
    "pull",
    "pump",
    "punch",
    "puncture",
    "punish",
    "push",
    "question",	"queue",	 	 
    "race",
    "radiate",
    "rain",
    "raise",
    "reach",
    "realise",
    "receive",
    "recognise",
    "record",
    "reduce",
    "reflect",	"refuse",
    "regret",
    "reign",
    "reject",
    "rejoice",
    "relax",
    "release",
    "rely",
    "remain",
    "remember",
    "remind",	"remove",
    "repair",
    "repeat",
    "replace",
    "reply",
    "report",
    "reproduce",
    "request",
    "rescue",
    "retire",
    "return",	"rhyme",
    "rinse",
    "risk",
    "rob",
    "rock",
    "roll",
    "rot",
    "rub",
    "ruin",
    "rule",
    "rush",
    "sack",
    "sail",
    "satisfy",
    "save",
    "saw",
    "scare",
    "scatter",
    "scold",
    "scorch",
    "scrape",
    "scratch",
    "scream",
    "screw",
    "scribble",
    "scrub",
    "seal",
    "search",
    "separate",
    "serve",
    "settle",
    "shade",
    "share",
    "shave",
    "shelter",	"shiver",
    "shock",
    "shop",
    "shrug",
    "sigh",
    "sign",
    "signal",
    "sin",
    "sip",
    "ski",
    "skip",
    "slap",
    "slip",
    "slow",
    "smash",
    "smell",
    "smile",
    "smoke",
    "snatch",
    "sneeze",
    "sniff",
    "snore",
    "snow",
    "soak",	"soothe",
    "sound",
    "spare",
    "spark",
    "sparkle",
    "spell",
    "spill",
    "spoil",
    "spot",
    "spray",
    "sprout",
    "squash",
    "squeak",
    "squeal",
    "squeeze",
    "stain",
    "stamp",
    "stare",
    "start",
    "stay",
    "steer",
    "step",
    "stir",
    "stitch",	"stop",
    "store",
    "strap",
    "strengthen",
    "stretch",
    "strip",
    "stroke",
    "stuff",
    "subtract",
    "succeed",
    "suck",
    "suffer",
    "suggest",
    "suit",
    "supply",
    "support",
    "suppose",
    "surprise",
    "surround",
    "suspect",
    "suspend",
    "switch",
    "talk",
    "tame",
    "tap",
    "taste",
    "tease",
    "telephone",
    "tempt",
    "terrify",
    "test",
    "thank",	"thaw",
    "tick",
    "tickle",
    "tie",
    "time",
    "tip",
    "tire",
    "touch",
    "tour",
    "tow",	"trace",
    "trade",
    "train",
    "transport",
    "trap",
    "travel",
    "treat",
    "tremble",
    "trick",
    "trip",	"trot",
    "trouble",
    "trust",
    "try",
    "tug",
    "tumble",
    "turn",
    "twist",
    "type",
    "undress",
    "unfasten",	"unite",
    "unlock",	"unpack",
    "untidy",	"use",
    "vanish",	"visit",	 	 
    "wail",
    "wait",
    "walk",
    "wander",
    "want",
    "warm",
    "warn",
    "wash",	"waste",
    "watch",
    "water",
    "wave",
    "weigh",
    "welcome",
    "whine",
    "whip",	"whirl",
    "whisper",
    "whistle",
    "wink",
    "wipe",
    "wish",
    "wobble",
    "wonder",	"work",
    "worry",
    "wrap",
    "wreck",
    "wrestle",
    "wriggle",
    "x-ray",	 	 	 
    "yawn",	"yell",	 	 
    "zip",	"zoom"
    ] 

adjectivesSet = S.fromList adjectives

adjectives = ["adorable",

    "adventurous",

    "aggressive",

    "agreeable",

    "alert",

    "alive",

    "amused",

    "angry",

    "annoyed",

    "annoying",

    "anxious",

    "arrogant",

    "ashamed",

    "attractive",

    "average",

    "awful",

    "bad",

    "beautiful",

    "better",

    "bewildered",

    "black",

    "bloody",

    "blue-eyed",

    "blushing",

    "bored",

    "brainy",

    "brave",

    "breakable",

    "bright",

    "busy",

    "calm",

    "careful",

    "cautious",

    "charming",

    "cheerful",

    "clean",

    "clear",

    "clever",

    "cloudy",

    "clumsy",

    "colorful",

    "combative",

    "comfortable",

    "concerned",

    "condemned",

    "confused",

    "cooperative",

    "courageous",

    "crazy",

    "creepy",

    "crowded",

    "cruel",

    "curious",

    "cute",

    "dangerous",

    "dark",

    "dead",

    "defeated",

    "defiant",

    "delightful",

    "depressed",

    "determined",

    "different",

    "difficult",

    "disgusted",

    "distinct",

    "disturbed",

    "dizzy",

    "doubtful",

    "drab",
    "dull", 
    "eager",
    "easy",

    "elated",

    "elegant",

    "embarrassed",

    "enchanting",

    "encouraging",

    "energetic",

    "enthusiastic",

    "envious",

    "evil",

    "excited",

    "expensive",

    "exuberant",

    "fair",

    "faithful",

    "famous",

    "fancy",

    "fantastic",

    "fierce",

    "filthy",

    "fine",

    "foolish",

    "fragile",

    "frail",

    "frantic",

    "friendly",

    "frightened",

    "funny",

    "gentle",

    "gifted",

    "glamorous",

    "gleaming",

    "glorious",

    "good",

    "gorgeous",

    "graceful",

    "grieving",

    "grotesque",

    "grumpy",

    "handsome",

    "happy",

    "healthy",

    "helpful",

    "helpless",

    "hilarious",

    "homeless",

    "homely",

    "horrible",

    "hungry",

    "hurt",

    "ill",

    "important",

    "impossible",

    "inexpensive",

    "innocent",

    "inquisitive",

    "itchy",

    "jealous",

    "jittery",

    "jolly",

    "joyous",

    "kind",

    "lazy",

    "light",

    "lively",

    "lonely",

    "long",

    "lovely",

    "lucky",

    "magnificent",

    "misty",

    "modern",

    "motionless",

    "muddy",

    "mushy",

    "mysterious",

    "nasty",

    "naughty",

    "nervous",

    "nice",

    "nutty",

    "obedient",

    "obnoxious",

    "odd",

    "old-fashioned",

    "open",

    "outrageous",

    "outstanding",

    "panicky",

    "perfect",

    "plain",

    "pleasant",

    "poised",

    "poor",

    "powerful",

    "precious",

    "prickly",

    "proud",

    "putrid",

    "puzzled",

    "quaint",

    "real",

    "relieved",

    "repulsive",

    "rich",

    "scary",

    "selfish",

    "shiny",

    "shy",

    "silly",

    "sleepy",

    "smiling",

    "smoggy",

    "sore",

    "sparkling",

    "splendid",

    "spotless",

    "stormy",

    "strange",

    "stupid",

    "successful",

    "super",

    "talented",

    "tame",

    "tasty",

    "tender",

    "tense",

    "terrible",

    "thankful",

    "thoughtful",

    "thoughtless",

    "tired",

    "tough",

    "troubled",

    "ugliest",

    "ugly",

    "uninterested",

    "unsightly",

    "unusual",

    "upset",

    "uptight",

    "vast",

    "victorious",

    "vivacious",

    "wandering",

    "weary",

    "wicked",

    "wide",

    "wild",

    "witty",

    "worried",

    "worrisome",

    "wrong",

    "zany",

    "zealous"
    ]


